# Generated by Django 4.2.2 on 2024-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_floor_busy_place_floor_empty_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
