# Generated by Django 4.2.2 on 2024-07-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
