# Generated by Django 4.2.2 on 2024-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
