# Generated by Django 4.2.2 on 2024-07-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bed',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='floor',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
